server:
  port: 4000
  ssl:
    key-store: ./src/main/resources/ssl/baeldung.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: baeldung
    enabled: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

spring:
  application:
    name: PasteBinService
  datasource:
    url: jdbc:postgresql://localhost:5432/information_security_project
    username: postgres
    password: postgress
  jpa:
    hibernate:
      dll-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect